version: '3.4'

services:
  productdb:
    container_name: productdb
    environment:
      - POSTGRES_USER0=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=productdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=majeed.dl@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - productdb
